trigger: 
  - main
  - feature*

variables:
  - name: AZSUBSCRIPTION  
    value: AZDOManaged
stages:
  - stage: AppBuild 
    condition: always()
    jobs:
    - job: BuildWar    
      workspace:
        clean: all
      pool:
        name: CloudopsPool
      steps:    
      - task: Bash@3
        inputs:
          targetType: 'filePath'
          filePath: deployscripts/buildJob.sh
        env:
          buildNumber: $(Build.BuildNumber)
          buildDir: $(Pipeline.Workspace) 
      - task: CopyFiles@2
        displayName: 'Copy Files to artifact directory'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/target/*.?(war|jar)'
          TargetFolder: $(Build.ArtifactStagingDirectory)
      - upload: $(Build.ArtifactStagingDirectory)
        artifact: petclinic
    
  - stage: deployToDev
    pool:
      name: CloudopsPool      
    condition: succeeded()
    jobs: 
      - deployment: VMDeploy
        displayName: Deploy to Dev Web
        environment:
          name: CloudOpsDev
          resourceType: VirtualMachine
        strategy:
          runOnce:            
            preDeploy:
              steps:
              - download: current
                artifact: petclinic
              - script: echo initialize, cleanup, backup, install certs
            deploy:
              steps:
              - task: Bash@3
                inputs:
                  targetType: 'inline'
                  script: |
                    echo "Pipeline workspace is $(Pipeline.Workspace)"                    
                    echo "Artifacts directlry is $(System.ArtifactsDirectory)"
                    ls -l $(System.ArtifactsDirectory)
                    echo "Current dir is $(pwd)"
                    ls -l 
                    # Modify deployment script based on the app type
                    echo "Starting deployment script run"
                    sudo cp '$(Pipeline.Workspace)/petclinic/**/target/*.war /opt/tomcat/webapps/petclinic.war 

